services:
  - type: web
    name: healthnexus-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8000
      - key: FRONTEND_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 15m
      - key: JWT_REFRESH_EXPIRE
        value: 7d
      - key: BCRYPT_SALT_ROUNDS
        value: 10
      - key: GEMINI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
